### ISSUE TITLE
CRFsuite cannot tag concurrently

### ISSUE THREAD

**Issue by tavianator** [chokkan/crfsuite#35]
CRFsuite uses a single tagger instance per model, created [here](https://github.com/chokkan/crfsuite/blob/556603969544dc9c6c43079a5ca59fb3bfef9d81/lib/crf/src/crf1d_tag.c#L490) and returned from `get_tagger()` [here](https://github.com/chokkan/crfsuite/blob/556603969544dc9c6c43079a5ca59fb3bfef9d81/lib/crf/src/crf1d_tag.c#L394).  As such, it is not safe to tag data from multiple threads at once, because the tagging process mutates the tagger.

It would be a simple enough change to create a new tagger instance in `get_tagger()` every time.  Would that be enough to ensure thread safety?

**Comment by chokkan** [comment]
Initially, I did not consider the situation where a tagger is used by multiple threads. Your patch does not introduce any extra problem but provides a more reasonable spec. Thanks a lot.
