### ISSUE TITLE
Question about duplicate features

### ISSUE THREAD

**Issue by usptact** [chokkan/crfsuite#55]
Perhaps I missed it in the documentation but it is not clear for me how duplicate features are treated in CRFSuite. Suppose my data is like this:

...
label0 A C D
label1 A B C D A
label2 B C C D C
label3 B C D E
...

Here we see that 2nd and 3rd example have duplicate features. The 2nd has the feature A duplicated while the 3rd example has the feature C three times.

I would really hope that duplicated features get the weight incremented. I hope my example is equivalent to:

...
label0 A C D
label1 A:2 B C D
label2 B C:3 D
label3 B C D E
...

Thanks

**Comment by bzaar** [comment]
Yes, that's exactly what the [manual says](http://www.chokkan.org/software/crfsuite/manual.html#idp8853717120). Duplicating attributes is equivalent to multiplying their weights.
