### ISSUE TITLE
Increment the version number?

### ISSUE THREAD

**Issue by usptact** [chokkan/crfsuite#58]
I am very happy to see crfsuite being improved since very recently! Thanks a lot, chokkan! I don't know the policy of version numbers but wouldn't it be great to increment the version number to reflect the relatively large number of pull requests being integrated?

Thanks a lot for maintaining the software!

**Comment by chokkan** [comment]
Yes. I will bump the version number and make a release. I need to check and prepare various things before making a release. It's been about five years since I released the previous version.

Thank you for supporting this software.
