### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by LeenaShekhar** [chokkan/crfsuite#78]
According to the INSTALL file:

. `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.  If you're
     using `csh' on an old version of System V, you might need to type
     `sh ./configure' instead to prevent `csh' from trying to execute
     `configure' itself. 

I cannot locate the configure.sh in the directory, and autoconf does not do anything. Please let me know howto fix it.

**Comment by Kiennh** [comment]
you must to run autogen.sh firsh

**Comment by cynthia** [comment]
The comment above is correct. I'll do an update on the documentation to make that clear.
