### ISSUE TITLE
How can I add more features?

### ISSUE THREAD

**Issue by LeenaShekhar** [chokkan/crfsuite#79]
I want to add features like "isCapital", "isNumber" etc. Could you please tell me how can I do that?

**Comment by usptact** [comment]
You need to write a script which will be function of the word. If the word starts with capital letter (or all caps?), you generate an arbitrary feature, say C-ISCAPITAL. Similarly for "isNumber".

**Comment by LeenaShekhar** [comment]
Thank you. I will implement it- I think I got the idea. Once done, I will add details to this thread
