### ISSUE TITLE
Condition should be ==

### ISSUE THREAD

**Issue by rainarch** [chokkan/crfsuite#89]
https://github.com/chokkan/crfsuite/blob/8c0028c5070546a5fc08d2c8175ab244c618f35f/lib/crf/src/crf1d_model.c#L779

**Comment by usptact** [comment]
Dupe #73

**Comment by jlerouge** [comment]
Well spotted !

**Comment by jlerouge** [comment]
#74

**Comment by chokkan** [comment]
Sorry for not merging the PRs for so long...

**Comment by usptact** [comment]
@chokkan Thank you so much for the software package (I used it almost daily) and for maintaining it!
