### ISSUE TITLE
start with CRF suite in windows

### ISSUE THREAD

**Issue by fatemehbashiri** [chokkan/crfsuite#99]
how to start with CRF suite in windows I don't know how to make a train and test file
i cant write this file for learning and testing and its vague for me to work with that.

**Comment by jlerouge** [comment]
Have you read the [tutorial](http://www.chokkan.org/software/crfsuite/tutorial.html) ?

**Comment by cynthia** [comment]
No feedback from reported, looks like the tutorial worked.
